CREATE ROLE iot_role;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE TRIGGER to iot_role;

--CREATE SCHEMA/USER FOR NODE CS
CREATE USER device IDENTIFIED BY iotdevice 
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users;
GRANT iot_role TO device;